### ISSUE TITLE
Feature request: Set working folder

### ISSUE THREAD

**Issue by ZBlocker655** [Tyriar/vscode-shell-launcher#12]
I can't add Docker Quickstart Terminal (from the Docker Toolbox) because you need to set the working folder to "C:\Program Files\Docker" otherwise the terminal exits with an error.

**Comment by Ash258** [comment]
It would be much easier to set working folder on active file's  folder as [terminal here](https://marketplace.visualstudio.com/items?itemName=Tyriar.vscode-terminal-here "terminal here")

**Comment by Tyriar** [comment]
You can set the working folder in user settings via `terminal.integrated.cwd`, does that meet your needs?

**Comment by ZBlocker655** [comment]
No, I don't think so because if I understand correctly, that is a global setting that is applied to all terminals.  What I really could use is the ability to set it _per terminal_, i.e. with shellLauncher like so:
```javascript
{
    "shell": "C:\\Program Files\\Git\\bin\\bash.exe",
    "args": [
        "--login",
        "-i \"C:\\Program Files\\Docker Toolbox\\start.sh\""
    ],
    "label": "Docker Quickstart",
    "cwd": "C:\\Program Files\\Docker"
}
```

**Comment by Tyriar** [comment]
Oh, I think that's out of scope for this extension. I think you might be better off with https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals

**Comment by ZBlocker655** [comment]
I don't understand why that would be out of scope here, especially if it's preventing me from launching a certain shell the way I need to. 

Looking in the vscode typings file I see two overloads of the function `createTerminal` [here](https://github.com/Microsoft/vscode/blob/1299efd2084504f09c89c8f74fd48790e9f65fe4/src/vs/vscode.d.ts#L4918).  Wouldn't the second one suit the purpose, since it allows a full options object including the `cwd` property?

**Comment by Tyriar** [comment]
On second thought you're right 👍

**Comment by kentnek** [comment]
Hi, I'm trying to add support for `cwd` on my own fork, but I can't test it since `cwd` does not exist in `TerminalOptions` in the latest release version (1.10.0) of `vscode.d.ts`. 

The property was only added in Microsoft/vscode#38132. How can I use this newer version?

**Comment by Tyriar** [comment]
@kentnek change the `vscodeEngine` property in `package.json` to 1.19.0 and run `rm -rf node_modules && npm i`

**Comment by kentnek** [comment]
Ah thanks, since this is the first time I'm editing an extension's code, I didn't know that I needed to change the property `engine.vscode`. Nevertheless, version `1.19.0` still doesn't have the 'TerminalOptions.cwd` property. Is there some place where I can find the latest version number?

**Comment by Tyriar** [comment]
@kentnek ah I thought it was already released because it was a while ago. It's not yet because this is a particularly long iteration due to the holidays. You can work on it using [Insiders](http://code.visualstudio.com/insiders) but should probably wait until 1.20 is released before we publish.
