### ISSUE TITLE
Allow ENV variable setting before starting terminal

### ISSUE THREAD

**Issue by wolf99** [Tyriar/vscode-shell-launcher#20]
VsCode's default terminal settings introduced `terminal.integrated.env.windows` allowing us to set environment variables before starting the terminal. This is fine until, with shell-launcher, we need different env vars per shell.

I have tried something like the following but it seems to just ignore it (also tried adding `"-i"` to the `args` but no dice) :

```json
    "shellLauncher.shells.windows": [
        {
            "label": "MSYS2",
            "shell": "C:\\msys64\\usr\\bin\\bash.exe",
            "env": {
                "CHERE_INVOKING": 1,
                "MSYSTEM": "MINGW64",
                "MSYS2_PATH_TYPE": "inherit"
            },
            "args": [
                "--login"
            ]
        },
       //...
```

This SO question shows what the env vars used above are for: https://stackoverflow.com/questions/45836650/how-do-i-integrate-msys2-shell-into-visual-studio-code-on-window

As far as I can tel `"cwd": "${cwd}"` doesn't seem to work to override chere invoking in this particular case (basically the msys bash runs `cd ~` after it opens.)

**Comment by Tyriar** [comment]
@DoctorJew thanks for the ping, by the way you can add "Fixes #20" in your commit message to automatically close the issue. Normally I edit this into the PR description but missed this one 😃
