### ISSUE TITLE
Cygwin - terminated with exit code 1 ?

### ISSUE THREAD

**Issue by SheepDomination** [Tyriar/vscode-shell-launcher#23]
Oh I see why @Tyriar promoted this based on a question I had for VSCode, it's his tool.
I have the extension installed but; after setting up Cygwin and existing from a Cygwin Terminal I get the error mentioned a few times with VSCode and that is [this](https://github.com/Microsoft/vscode/issues/10353). 

Why am I getting this error only with Cygwin ? As well I'd like to disable showing of the path of the shell I want to open within shell-launcher; and change the color of each shell name in the list.

**Comment by Tyriar** [comment]
@SheepDomination does it happen when you configure a normal terminal to launch cygwin? Can you share your settings.json file?

**Comment by SheepDomination** [comment]
@Tyriar Before Before changing to Shell-launcher I don't recall having the `terminated with exit code 1` error with Cygwin. This is the section of my `settings.json` file, I hope it helps ?

` "shellLauncher.shells.windows": [
      {
        "shell": "C:\\Windows\\System32\\cmd.exe",
        "label": "cmd"
      },
      {
        "shell": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
        "label": "PowerShell"
      },
      {
        "shell": "C:\\Windows\\System32\\bash.exe",
        "label": "WSL Bash"
      },
      {
        "shell": "C:\\cygwin64\\Cygwin.bat",
        "label": "Cygwin Bash"
      }
    ]`

**Comment by Tyriar** [comment]
Do you need to use cygwin64\bin\bash.exe? https://github.com/Microsoft/vscode/issues/14977

**Comment by SheepDomination** [comment]
The solution for issue #14977 as you posted, worked; the error has disappeared.  I suppose the *shell arguments* are necessary for this issue. 

Although I don't quite understand what you mean by, *Do you need to use cygwin64\bin\bash.exe?* **?**
