### ISSUE TITLE
Support WoW64 path conversion

### ISSUE THREAD

**Issue by Tyriar** [Tyriar/vscode-shell-launcher#28]
When running 32-bit VS Code on 64-bit Windows the path needs to be sysnative. Basically we want to do this:

https://github.com/Microsoft/vscode/blob/c93565448ab9988cbeb8a0eac4e3304dc97cc844/src/vs/workbench/parts/terminal/electron-browser/terminalConfigHelper.ts#L214-L222

Context: https://github.com/Tyriar/vscode-shell-launcher/issues/27

**Comment by jabalv** [comment]
#41 should solve this!
