### ISSUE TITLE
A little help

### ISSUE THREAD

**Issue by versamodule** [Tyriar/vscode-shell-launcher#29]
Probably going to get spanked for asking this here, as there is no issue. 
I have been using this as my shell. 

`    
"terminal.integrated.shell.windows": "C:/msys32/usr/bin/bash.exe",
    "terminal.integrated.shellArgs.windows": [
        "--login",
    ],
    "terminal.integrated.env.windows": {
        "CHERE_INVOKING": "1",
        "MSYSTEM": "MINGW32",
    }
`   

 

Recently, I had to use VSC to include another platform and now i need two shell's. I just cannot figure out how to add this one with the default to get them both to work as they should. 

I have done this so far. 

    "shellLauncher.shells.windows": [
        {
            "shell": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
            "label": "PowerShell"
        },
        {
            "shell": "C:/msys32/usr/bin/bash.exe",
            "label": "ESP32 Shell",
            "args": ["--login"],
            "terminal.integrated.env.windows": {
                "CHERE_INVOKING": "1",
                "MSYSTEM": "MINGW32",
            },
        },
        
        
     ]

**Comment by versamodule** [comment]
I figured it out, sorry.

**Comment by fmonroe** [comment]
@versamodule Can you share the solution, please ?
