### ISSUE TITLE
Feature Request: Allow naming terminals like Terminal Tabs does.

### ISSUE THREAD

**Issue by gerane** [Tyriar/vscode-shell-launcher#3]
It would be nice to allow setting custom names for terminals in the config, either by using the label name or adding a name property. I have multiple PowerShell Terminal types, but they all display as **powershell.exe** in the drop down. It makes it difficult to know which terminal is which.

**Comment by Tyriar** [comment]
Opening up to PRs, I think this would be best as a new `shellLauncher.launchNamed` command so people who don't want named done get an additional dialog.

**Comment by gerane** [comment]
I know for my use case, I'd rather be able to name it in the config. Right now all of these PowerShell 64bit, 32bit, PowerShell core, or one with custom arguments would all show PowerShell.exe in the drop down. I was forgetting which one was which.

In the config it would be nice to set the name, or have the label act as the name so you can distinguish the terminals from one another when you have multiple open at once. So those examples might be PowerShell, PowerShell x32, PowerShell Core, and PowerShell NoProfile.

**Comment by fabiospampinato** [comment]
Isn't this implemented already in the form of the `launchName` configuration option?

**Comment by Tyriar** [comment]
Yep, was missing the annotation in https://github.com/Tyriar/vscode-shell-launcher/pull/10 to auto close the issue.
