### ISSUE TITLE
How to pass the file name as argument?

### ISSUE THREAD

**Issue by fmonroe** [Tyriar/vscode-shell-launcher#30]
Using the _regular_ shell I can specify the file name as an argument, like this:
`"terminal.integrated.shellArgs.powershell": ["${file}"]`
Exactly how can I achieve the same and pass on the file name using this extension?
Thanks.

**Comment by fmonroe** [comment]
Correction: 
Using the regular shell **I WISH I COULD** specify the file name as an argument, like this:
"terminal.integrated.shellArgs.powershell": ["${file}"]

> Apparently there is an open issue for this. 

Can I achieve what I want and pass on the file name _using this extension_?
Here is what I tried:
```
   "shellLauncher.shells.windows": [
      {
         "shell": "C:\\Windows\\System32\\cmd.exe",
         "label": "Command prompt"
      },
      {
         "shell": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
         "label": "PowerShell"
      },
      {
         "shell": "C:\\Program Files\\PowerShell\\6-preview\\pwsh.exe",
         "args": ["C:\\Users\\frank\\OneDrive\\bin\\mytask.ps1", "${file}"],
         "label": My task"
      }
```
The formal argument received by the PS script is `${file}` - it has not been replaced by its value.

**Comment by Tyriar** [comment]
@fmonroe is `${file}` meant to be the active file? As long as the syntax is consistent with tasks/debug/etc., this seems like a feature request that should be added to the main repo. This extension should just work then. https://github.com/Microsoft/vscode/issues/new?template=feature_request.md
