### ISSUE TITLE
retain same type of shell for after restart

### ISSUE THREAD

**Issue by LeonardAB** [Tyriar/vscode-shell-launcher#31]
I am not sure if this is a bug or an intended behavior, but it'd be great if the expected behavior could be implemented.

**Steps to reproduce:**
1. set the vscode default shell (`F1` - `Terminal: Select default shell`), choose anything (e.g. Git Bash)
2. open a shell using Shell launcher, but choose something that is not the one chosen in step one (e.g. choose Powershell)
3. Close VS code
4. Reopen the VS code (the same folder / workspace / file opened in step 1-3)

**Expected behavior**
The previously opened terminal is opened on the panel  (in this case, Powershell)

**Actual behavior**
The terminal is opened on the panel, but the default one (in this case, Git Bash)

This happens also when several terminals were opened. E.g. if I opened Git Bash, cmd, and Powershell, after I reopened VSCode, the three of them became the default terminal.

Shell Launcher version: 0.2.0
Thank you!

**Comment by Tyriar** [comment]
This is by design for now
