### ISSUE TITLE
Feature Request: Allow running script before launching bash shell

### ISSUE THREAD

**Issue by remware** [Tyriar/vscode-shell-launcher#36]
I have a use case where docker installation needs to execute a script before launching interactive bash terminal: start.sh, is this possible?
Another option would be to add a setting that allows to run specific script. For example "profile": "/home/user/start.sh" that is set to default like "/home/user/bash_profile and then use the existing bash -l argument

Actually this might not be needed, I managed to hack settings like follow:
 "shell": "C:\\Program Files\\Git\\bin\\bash.exe",
  "label": "Docker bash",
  "args" : ["--login", "-i", "C:\\Program Files\\Docker Toolbox\\start.sh"],
   "cwd"  : "C:\\Program Files\\Docker Toolbox\\"

**Comment by Tyriar** [comment]
> Actually this might not be needed, I managed to hack settings like follow

Something along those lines is what I was going to suggest 😃, glad you got it working 👍
