### ISSUE TITLE
Preserve multiple shell histories

### ISSUE THREAD

**Issue by laakejs** [Tyriar/vscode-shell-launcher#38]
When I have multiple different shells open (cmd, wsl, ...) and I close vscode, just the shell history of the currently choosen shell is preserved. For example if I have a cmd and a wsl open, with the cmd as the current selection and close vscode, the shell history of the wsl will be lost.
Any suggestions how to preserve both of them?

**Comment by Tyriar** [comment]
Shell history is maintained by the shell and is typically related to how the shell shuts down, I don't think vscode or this extension has any control over that.
