### ISSUE TITLE
PowerShell Core does not appear

### ISSUE THREAD

**Issue by jasper-zanjani** [Tyriar/vscode-shell-launcher#39]
On both my Windows PC and my Mac, PowerShell Core does not appear in Shell Launcher's dropdown. It does, however, appear, when you want to select the default shell. On my Mac the pwsh executable is in /etc/shells.

**Comment by Tyriar** [comment]
I'm not planning on doing any further improvements to this extensions but instead improve the core, created https://github.com/microsoft/vscode/issues/79313 to track that.
