### ISSUE TITLE
Trouble launching as PowerShell V2

### ISSUE THREAD

**Issue by The-Experimentalist** [Tyriar/vscode-shell-launcher#40]
I tried to add this:

        {
            "shell": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
            "args": "-Version 2",
            "label": "PowerShell 2.0"
        },

to the shellLauncher.shells.windows section in settings.json but I get the message: 
Running the contributed command: 'shellLauncher.launch' failed.

Have I got the syntax wrong?

**Comment by Tyriar** [comment]
@TylerLeonhardt can probably help with this, is `powershell.exe -Version 2` valid?

**Comment by TylerLeonhardt** [comment]
It is valid... but Windows PowerShell 2.0 is [deprecated](https://devblogs.microsoft.com/powershell/windows-powershell-2-0-deprecation/).
