### ISSUE TITLE
Configurations not working with slashes or backslashes

### ISSUE THREAD

**Issue by fakkoweb** [Tyriar/vscode-shell-launcher#51]
Hello,

I am having a hard time making this extension work.

First of all, as soon as I install it, I can already see cmd.exe and powershell.exe terminals ready... but NONE are set into settings.json.

If I set a new one into settings.json, then ONLY THAT ONE will be available. So I need to re-add all the terminals that I was able to see before modifying settings.json? Why is that??

Secondly... I cannot set a PATH into the "shell:" key.
If I put any "\\" or "/", Shell Launcher WILL NOT see it. With the following configuration I can only launch cmd.exe. It does NOT see the other one.

`    "shellLauncher.shells.windows": [
        {
            "shell": "cmd.exe",
            "label": "Cmd"
        },
        {
            "shell": "C:\\Program Files\\Git\\bin\\bash.exe",
            "label": "Git bash"
        },
]
`

And if I remove both, Shell Launcher will show me again cmd.exe and powershell.exe as it was on installation.

Please help because this is driving me crazy

**Comment by Tyriar** [comment]
If you change the setting by using tab you can have it scaffolded out to the default value. This should behave exactly the same as the default value when it's not set so it's a good starting point:

![501a4069-97e4-4f24-bb39-14a3de661d84](https://user-images.githubusercontent.com/2193314/78675395-db222980-7899-11ea-96f7-e2551e03e86a.gif)

> If I set a new one into settings.json, then ONLY THAT ONE will be available. So I need to re-add all the terminals that I was able to see before modifying settings.json? Why is that??

So you can control what shows up there.

---

I've said in other issues I'm trying not to spend more effort on this as any time should be directed to a built-in feature https://github.com/microsoft/vscode/issues/45444
