### ISSUE TITLE
Cannot insert double quotes into shell arguments

### ISSUE THREAD

**Issue by kkaja123** [Tyriar/vscode-shell-launcher#52]
When trying to insert quotation marks into an args string, Shell Launcher seems to try to escape the quotes before passing the args to the shell. 

Using cmd.exe as an example:
![image](https://user-images.githubusercontent.com/36752032/77025810-0e8b2b80-6960-11ea-800c-e0a60b7e9a20.png)

Escaping the quotes as usual, VSCode inserts the quotation marks as expected.
![image](https://user-images.githubusercontent.com/36752032/77026071-c28cb680-6960-11ea-8ffe-2b244d831434.png)

By the time the args string reaches the shell, there are extra `\` characters in front of the `"` characters.
![image](https://user-images.githubusercontent.com/36752032/77026154-f7990900-6960-11ea-85af-0508c905220d.png)

Without the quotation marks, the spaces in the string will cause the arguments to fail.

**Comment by Tyriar** [comment]
I'm not adding further feature to this extension as ay further investment should be directed to the feature request in core https://github.com/microsoft/vscode/issues/45444
