### ISSUE TITLE
Love the potential that this extension brings. But I have one major issue I need help with.

### ISSUE THREAD

**Issue by JustACodingNerd** [Tyriar/vscode-shell-launcher#56]
I just have one issue. From what I gather is that Shell Launcher is supposed to allow you to open any shell that you need to use in the terminal for a given project. Like, say I am working on node.js project. I can use a Git Bash terminal and test my js files there. Now let say I have to deal with a MongoDB server. The extension is not switching to Mongo Shell within VS Code.

```json
// Git Bash
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
// Mongo Shell
"terminal.integrated.shell.windows": "C:\\Program Files\\MongoDB\\Server\\4.2\\bin\\mongo.exe",
```
The Mongo Shell I added and I can now run a Mongo Shell in the terminal area.

```json
        {
            "shell": "C:\\Program Files\\MongoDB\\Server\\4.2\\bin\\mongo.exe",
            "label": "MongoDB Shell"
        }
```
I also added these lines to the end of the array in the settings.json file.

Everything here gives me a MongoDB Shell to work with and play within the VS Code. But the issue that I face now is that I cannot switch back to Git Bash to get back to working on my Node.js project.

I'm trying to make VS Code where I code everything in my quest to be MEVN developer.

Is there another step that I am missing? I have not made any real changes to the settings.json file without first putting comments to make sure I can undo anything that I break. Getting MongoDB Shell to run in VS Code is definitely a goal that I set to accomplish. Got that checked off. But now I cannot switch back to bash without deleting the related lines of code. I know that there has to be a way to make this work. 

This is the complete json file:
```json
{
    "explorer.confirmDragAndDrop": false,
    "files.autoSave": "afterDelay",
    "git.ignoreMissingGitWarning": true,
    "python.linting.enabled": false,
    "python.pythonPath": "C:\\Users\\Rafael\\Anaconda3",
    "window.zoomLevel": 0,
    "workbench.iconTheme": "material-icon-theme",
    "cSpell.userWords": [
        "backticks",
        "endregion",
        "quicksliver"
    ],
    // Command Prompt
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    // Git Bash
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    // Mongo Shell
    "terminal.integrated.shell.windows": "C:\\Program Files\\MongoDB\\Server\\4.2\\bin\\mongo.exe",
    
    "debug.node.autoAttach": "on",
    "gitHistory.logLevel": "Info",
    "explorer.confirmDelete": false,
    "git.enableSmartCommit": true,
    "shellLauncher.shells.windows": [

        {
            "shell": "C:\\Windows\\System32\\cmd.exe",
            "label": "cmd"
        },
        {
            "shell": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
            "label": "PowerShell"
        },
        {
            "shell": "C:\\Program Files\\Git\\bin\\bash.exe",
            "label": "Git bash"
        },
        {
            "shell": "C:\\Windows\\System32\\bash.exe",
            "label": "WSL Bash"
        },
        {
            "shell": "C:\\Program Files\\MongoDB\\Server\\4.2\\bin\\mongo.exe",
            "label": "MongoDB Shell"
        }

    ],
    "shellLauncher.shells.linux": [

        {
            "shell": "/bin/bash",
            "label": "bash"
        },
        {
            "shell": "/bin/zsh",
            "label": "zsh"
        },
        {
            "shell": "zsh",
            "args": [
                "-l"
            ],
            "label": "zsh login shell"
        },
        {
            "shell": "bash",
            "args": [
                "-l"
            ],
            "label": "bash login shell"
        }

    ]
}
```

**Comment by Tyriar** [comment]
For your particular case I recommend setting your primary shell to `terminal.integrated.shell.windows` and any secondary ones in the extension and use the picker there. The real fix for this is to integrate this sort of feature in vscode core: https://github.com/microsoft/vscode/issues/45444
