### ISSUE TITLE
Shell from msys2 runs in a separate window

### ISSUE THREAD

**Issue by TreasureMaster** [Tyriar/vscode-shell-launcher#58]
I have installed msys2 (rev. 03-Sep-2020). But the mintty terminal runs in a separate window. And bash from MinGW works the same way. At the same time bash from Cygwin opens in VS Code and works great. My settings:

`"shellLauncher.shells.windows": [
    {
      "shell": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
      "label": "PowerShell"
    },
    {
      "shell": "C:\\Program Files\\Git\\bin\\bash.exe",
      "label": "Git bash"
    },
    {
      "shell": "C:\\cygwin64\\Cygwin.bat",
      "label": "Cygwin Bash",
      "launchName": "cygwin"
    },
    {
      "shell": "C:\\msys64\\msys2_shell.cmd",
      "args": ["-mingw64"],
      "label": "MinGW64 mintty"
    }
  ]`

Is there any way to start a shell from msys2 in VS Code?

**Comment by Tyriar** [comment]
If it's launching in a different window it means you're using the wrong `shell` value, I don't think this can be a script for example. You should be able to find the answer by searching the internet as other people would have run into this as well.
