### ISSUE TITLE
HOWTO - Pick a Shell to Launch from Menu instead of Keyboard Shortcut?

### ISSUE THREAD

**Issue by ElSrJuez** [Tyriar/vscode-shell-launcher#59]
I am a Menu person contrary to a Keyboard person. It doesn't mean that I don't use _any_ shortcuts - I do - but when VSCode is not on your screen all the time it is hard to remember shortcuts you don't use very often.
Is it possible to pick a Shell to launch from a menu option in addition to a shortcut key?
Thanks.

**Comment by Tyriar** [comment]
Extensions can't contribute to the top menu bar unfortunately. We could potentially do this when https://github.com/microsoft/vscode/issues/79034 gets done but I've largely stopped work on this as its functionality will eventually be merged into core which would get it some more UI love https://github.com/microsoft/vscode/issues/45444
