### ISSUE TITLE
The terminal process command failed to launch 

### ISSUE THREAD

**Issue by wolf99** [Tyriar/vscode-shell-launcher#6]
I've just installed this extension in VS Code (on Windows 10) and am seeing this error message when attempting to switch to any shell using it.

For example, when in the editor and attempting to switch to the command prompt from powershell the error is

> The terminal process command `cmd` failed to launch  (exit code : 1)

 When in the terminal and attempting to switch to the command prompt from powershell the error is

> The terminal process command `cmd` failed to launch  (exit code : 3221225477)

My `settings.json` user settings contains the following:
```
{
    "shellLauncher.shells.windows": [
        {
        "shell": "bash",
        "args": [""],
        "label": "Bash Shell"
        },
        {
            "shell": "cmd",
            "args": [""],
            "label": "Command Prompt"
        }
    ]
}
```
Am I using this incorrectly?

**Comment by Tyriar** [comment]
@wolf99 you will need to put in the full path or a filename including extension as the `shell` value. Try these: https://code.visualstudio.com/docs/editor/integrated-terminal#_windows
