### ISSUE TITLE
shells configured in setting.json do not display in  Laucher dropdown list

### ISSUE THREAD

**Issue by zhanghuangbin** [Tyriar/vscode-shell-launcher#60]
I followed the basic setup ,chose the keybind: "CTRL+shit+` " and made sure that no keybind conflict.
![image](https://user-images.githubusercontent.com/57585975/104812871-3f6a1480-5840-11eb-82fb-6f942ba45f5d.png)

the following lines is a part of my setting.json configuration:

```json
{
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "shellLauncher.shells.windows": [
        {
            "shell": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
            "label": "PowerShell"
        },
        {
            "shell": "C:\\Windows\\System32\\cmd.exe",
            "label": "cmd"
        },
        {
            "shell": "D:\\software\\Git\\bin\\bash.exe",
            "label": "Git bash"
        },
        {
            "shell": "C:\\MinGW\\msys\\1.0\\bin\\sh.exe",
            "args": [
                "--login",
                "-i"
            ],
            "label": "msys bash"
        },
        {
            "shell": "C:\\Windows\\System32\\bash.exe",
            "label": "WSL Bash"
        }
    ]
}
```

I have configured several shells(cmd, powershell, msys-bash, git-bash and so on) in "shellLauncher.shells.windows" property of setting.json, but when  I press "CTRL+shit+` ",  the Laucher dropdown list shows, but only two options, "cmd" and "powershell" appear。

then, I changed "cmd" shell configuration's label from "cmd" to "cmd-test" and press   "CTRL+shit+` ", the laucher dropdown list option does not change. the "cmd" label still shows as "cmd" , not "cmd-test".

and then, I deleted all items in  "shellLauncher.shells.windows" property, and pressed keys to test, the Laucher dropdown list still shows with only two options, "cmd" and "powershell" 。
![image](https://user-images.githubusercontent.com/57585975/104812890-61639700-5840-11eb-8e10-4ca66e0cc256.png)

It seems that the  "shellLauncher.shells.windows" property does not function and I'm confused where the two dropdown list options , "cmd" and "powershell" comes from.

here is my vscode and os's info:

vscode: 1.52.1(user setup)

os: window 10

hoping for your reply. thanks!

**Comment by Tyriar** [comment]
Not sure what the issue is here, as it works fine for me (v0.4.1 of extension):

![image](https://user-images.githubusercontent.com/2193314/105031040-8f480780-5a09-11eb-9aa9-a945dee97c3f.png)

Note that shells in the list only show up if the paths are validated and definitely exist. Are you sure those paths are valid?

**Comment by zhanghuangbin** [comment]
Thanks for reply.
sorry, that issue is my problem. I installed the plugin in other laptop and it worked. I found that the setting.json file I'm editing is  the  workplace's  setting.json. I edit the settings from the wrong entry.
![image](https://user-images.githubusercontent.com/57585975/105170008-4c944580-5b57-11eb-8fda-e979c826c0cd.png)

**Comment by Tyriar** [comment]
Makes sense, thanks for the follow up 👍
