### ISSUE TITLE
Feature request: Option to specify title of the shell window

### ISSUE THREAD

**Issue by cveld** [Tyriar/vscode-shell-launcher#65]
Currently the shell window's title is set to the executable that is run. E.g. when `pwsh` is run, the title of the shell reads `pwsh`.

When I run many shells through Shell Launcher it quickly becomes impossible to differentiate the running shells.

It would be great to be able to set a custom title so that every launched shell can be differentiated.

**Comment by Tyriar** [comment]
@cveld this extension is deprecated at this point in favor of the terminal profiles feature built-in to VS Code https://code.visualstudio.com/docs/editor/integrated-terminal#_terminal-profiles
