### ISSUE TITLE
Scrollbar of terminal disappear

### ISSUE THREAD

**Issue by EbXpJ6bp** [Tyriar/vscode-shell-launcher#8]
- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
---

When I create a terminal using this extension, the scroll bar and scrolling ability disappears on the second and subsequent terminals.

![gif](https://user-images.githubusercontent.com/8474118/30508754-3ca24f24-9ad9-11e7-9b43-9a9e27b7ccb3.gif)

Config
```
    "shellLauncher.shells.windows": [{
            "shell": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
            "label": "PowerShell"
        }
       ...
]
```

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/34483

**Comment by EbXpJ6bp** [comment]
@Tyriar 
This issue is not a duplicate.

When create a terminal using this extension in v 1.16, the size of `xterm-scroll-area` class (html) will not be correctly got and the scrolling ability seems to be lost. I thought that it was a issue of the extension, but it seems not to be that.

In v1.17(4571d387c9fe2d19e833ff96aa99aac6f73c88d4), the terminal is not be created from the extension. 

Maybe vscode api is missing some kind of error.
![gif](https://user-images.githubusercontent.com/8474118/30572652-ffa8b9e8-9d29-11e7-8afe-5a8b0462a84c.gif)

I had to create this issue on vscode repo.

**Comment by Tyriar** [comment]
@EbXpJ6bp are you pointing to sysnative instead of system32?

**Comment by EbXpJ6bp** [comment]
@Tyriar no, I'm using following shell config which was copied from default `terminal.integrated.shell.windows`

```
    "shellLauncher.shells.windows": [{
            "shell": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
            "label": "PowerShell"
        }
       ...
]
```

`"terminal.integrated.shell.windows"` has not changed in setting.json.

**Comment by EbXpJ6bp** [comment]
resolved by https://github.com/Microsoft/vscode/issues/34554
