### ISSUE TITLE
Extension doesn't work, but no errors

### ISSUE THREAD

**Issue by Alpvax** [Tyriar/vscode-shell-launcher#9]
Any terminal windows I open through this extension generate a new terminal window, but none of them have a prompt.
On Windows 10 x64, tried with bash subsystem, powershell and cmd, all have the same result of a blank terminal.

**Comment by Tiberriver256** [comment]
Same thing for me. Any suggestions?

**Comment by Alpvax** [comment]
No dice. Already on the 64 bit version.
![image](https://user-images.githubusercontent.com/1474110/31710902-4db6881a-b3ee-11e7-8776-c2673d0d63be.png)

**Comment by sipsorcery** [comment]
Same problem.

**Comment by Mimetis** [comment]
exact same problem here :)

**Comment by Tyriar** [comment]
I think everyone was experiencing an issue in VS Code, not the extension. I'll close this off as a duplicate of https://github.com/Microsoft/vscode/issues/34554, please let me know if you're still seeing this after updating to 1.17.2.

**Comment by Mimetis** [comment]
Hey @Tyriar, the issue is still active. I'm on the 1.17.2, and still can't launch any terminal within Shell Launcher

**Comment by Tyriar** [comment]
@Mimetis ah I can reproduce, the paths on Windows should point to System32 since the 64-bit version was released.

**Comment by Tyriar** [comment]
Fixed in https://github.com/Tyriar/vscode-shell-launcher/commit/6e9593821ec7393c056b18a498ab20d08dbc6b05 and published 0.1.4, thanks for pinging me again 😃
